remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Muhammad Adil]
description: [I am an AI Engineer and Computer Vision Researcher working across Generative AI, Object Detection, and MLOps-driven deployment. My expertise spans from developing optimized YOLO-based detection systems for real-time edge deployment to architecting Retrieval-Augmented Generation (RAG) and Agentic AI frameworks for scalable, cloud-integrated solutions]
